### ISSUE TITLE
Extraction of IPTC metadata

### ISSUE THREAD

**Issue by eseifert** [eseifert/madam#10]

**Comment by eseifert** [comment]
Depends on #44

**Comment by seifertm** [comment]
Depends on #47

**Comment by eseifert** [comment]
Metadata that should be read and written:
- `Iptc.Application2.Credit`
- `Iptc.Application2.Source`
- `Iptc.Application2.Copyright`
- `Iptc.Application2.Contact`
- `Iptc.Application2.Caption`
- `Iptc.Application2.Headline`
- `Iptc.Application2.DateCreated`
- `Iptc.Application2.TimeCreated`
- `Iptc.Application2.Byline`
- `Iptc.Application2.BylineTitle`
- `Iptc.Application2.ExpirationDate`
- `Iptc.Application2.ExpirationTime`
- `Iptc.Application2.ReleaseDate`
- `Iptc.Application2.ReleaseTime`
- `Iptc.Application2.Keywords`
- `Iptc.Application2.Subject`
- `Iptc.Application2.ImageOrientation`
- `Iptc.Application2.Language`
